# Generated by Django 3.2.2 on 2021-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ism_ty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ism',
            name='ty',
            field=models.IntegerField(),
        ),
    ]
