# Generated by Django 3.2.2 on 2021-06-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210615_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
