# Generated by Django 3.2.2 on 2021-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='subject_uz',
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subject_ru',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
